# Generated by Django 5.1.4 on 2024-12-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('hits', models.IntegerField()),
                ('became_fan', models.IntegerField()),
                ('launch_expected_year', models.IntegerField()),
                ('height_mm', models.FloatField()),
                ('width_mm', models.FloatField()),
                ('thickness_mm', models.FloatField()),
                ('body_weight_g', models.FloatField()),
                ('display_type', models.CharField(max_length=100)),
                ('pixels_x', models.IntegerField()),
                ('pixels_y', models.IntegerField()),
                ('display_size_inches', models.FloatField()),
                ('screen_to_body_ratio', models.FloatField()),
                ('ram_gb', models.FloatField()),
                ('main_camera_single_mp', models.FloatField()),
                ('selfie_camera_single_mp', models.FloatField()),
                ('sound_3_5mm_jack', models.BooleanField()),
                ('comms_bluetooth', models.CharField(max_length=100)),
                ('comms_nfc', models.BooleanField()),
                ('battery_capacity_mah', models.IntegerField()),
                ('price_usd', models.FloatField()),
            ],
        ),
    ]
