# Generated by Django 5.1.4 on 2024-12-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0003_rename_phones_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='main_camera_single_mp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='selfie_camera_single_mp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
