# Generated by Django 5.1.4 on 2024-12-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0004_alter_phone_main_camera_single_mp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('processor_brand', models.CharField(max_length=100)),
                ('processor_tier', models.CharField(max_length=100)),
                ('num_cores', models.IntegerField()),
                ('num_threads', models.IntegerField()),
                ('ram_memory', models.FloatField()),
                ('primary_storage_type', models.CharField(max_length=100)),
                ('primary_storage_capacity', models.IntegerField()),
                ('secondary_storage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_storage_capacity', models.IntegerField(blank=True, null=True)),
                ('gpu_brand', models.CharField(max_length=100)),
                ('gpu_type', models.CharField(max_length=100)),
                ('is_touch_screen', models.BooleanField()),
                ('display_size', models.FloatField()),
                ('resolution_width', models.IntegerField()),
                ('resolution_height', models.IntegerField()),
                ('operating_system', models.CharField(max_length=100)),
                ('year_of_warranty', models.IntegerField()),
            ],
        ),
    ]
