# Generated by Django 5.1.4 on 2024-12-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0005_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='year_of_warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
