# Generated by Django 5.1.4 on 2024-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0006_phone_year_of_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='year_of_warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
