# Generated by Django 5.1.4 on 2024-12-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0007_alter_laptop_year_of_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('processor_brand', models.CharField(max_length=100)),
                ('num_processor', models.IntegerField()),
                ('processor_speed', models.FloatField()),
                ('ram', models.FloatField()),
                ('memory_inbuilt', models.IntegerField()),
                ('battery_capacity', models.IntegerField()),
                ('charger', models.CharField(max_length=100)),
                ('charging', models.CharField(max_length=100)),
                ('display_size_inches', models.FloatField()),
                ('pixel', models.CharField(max_length=100)),
                ('resolution_width', models.IntegerField()),
                ('resolution_height', models.IntegerField()),
                ('ppi', models.FloatField()),
                ('frequency_display_hz', models.FloatField(blank=True, null=True)),
                ('primary_front_camera', models.FloatField(blank=True, null=True)),
                ('secondary_front_camera', models.FloatField(blank=True, null=True)),
                ('primary_rear_camera', models.FloatField(blank=True, null=True)),
                ('secondary_rear_camera', models.FloatField(blank=True, null=True)),
                ('os_brand', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('memory_card_upto', models.IntegerField(blank=True, null=True)),
                ('sim', models.CharField(max_length=100)),
                ('is_5G', models.BooleanField()),
                ('is_wifi', models.BooleanField()),
            ],
        ),
    ]
