# Generated by Django 5.1.4 on 2024-12-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0009_alter_tablet_battery_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('release_date', models.IntegerField()),
                ('max_resolution', models.IntegerField()),
                ('low_resolution', models.IntegerField()),
                ('effective_pixels', models.FloatField()),
                ('zoom_wide', models.IntegerField()),
                ('zoom_tele', models.IntegerField()),
                ('normal_focus_range', models.IntegerField(blank=True, null=True)),
                ('macro_focus_range', models.IntegerField(blank=True, null=True)),
                ('storage_included', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
