# Generated by Django 5.1.4 on 2024-12-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0011_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
