# Generated by Django 5.1.4 on 2024-12-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0013_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('phone', 'phone'), ('laptop', 'laptop'), ('tablet', 'tablet'), ('camera', 'camera')], max_length=50)),
                ('item_id', models.IntegerField()),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byt.user')),
            ],
        ),
    ]
