# Generated by Django 5.1.4 on 2024-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byt', '0015_remove_phone_became_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='became_fan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
